<?php

return [
  'trung' => [
    'fullname' => 'Phạm Chí Trung',
    'skill' => 'Web Developer | Designer',
    'id' => 'B1809424',
    'major' => 'Công nghệ thông tin',
    'university' => 'Đại học Cần Thơ',
    'email' => 'trungb1809424@student.ctu.edu.vn',
    'phone' => '0369 863 655',
    'facebook' => 'https://www.facebook.com/trungxi.it',
    'github' => 'https://www.github.com/trungxiit',
    'linkedin' => 'https://www.linkedin.com/in/trung-ph%E1%BA%A1m-101b871a2/',
  ],
  'khang' => [
    'fullname' => 'Nguyễn Vĩnh Khang',
    'skill' => 'Web Developer',
    'id' => 'B1809244',
    'major' => 'Công nghệ thông tin',
    'university' => 'Đại học Cần Thơ',
    'email' => 'khangb1809244@student.ctu.edu.vn',
    'phone' => '0962 435 100',
    'facebook' => 'https://www.facebook.com/khangcuteisme',
    'github' => '#',
    'linkedin' => '#',
  ],
  'long' => [
    'fullname' => 'Trương Hoàng Long',
    'skill' => 'Web Developer',
    'id' => 'B1809368',
    'major' => 'Công nghệ thông tin',
    'university' => 'Đại học Cần Thơ',
    'email' => 'longb1809368@student.ctu.edu.vn',
    'phone' => '0929 441 158',
    'facebook' => 'https://www.facebook.com/hoanglong.truong366',
    'github' => '#',
    'linkedin' => '#',
  ],
  'kien' => [
    'fullname' => 'Nguyễn Trung Kiên',
    'skill' => 'Web Developer',
    'id' => 'B1809361',
    'major' => 'Công nghệ thông tin',
    'university' => 'Đại học Cần Thơ',
    'email' => 'kienb1809361@student.ctu.edu.vn',
    'phone' => '0853 475 317',
    'facebook' => 'https://www.facebook.com/profile.php?id=100006040029598',
    'github' => '#',
    'linkedin' => '#',
  ],
];
